PARTS = [
  {
    "title": "PARTE I",
    "subtitle": "O Comando e a Estratégia",
    "epigraph": "Antes da encruzilhada, existe quem a criou. Antes do caminho, existe quem o guarda.",
    "books": [
      {
        "id": "sete-porteiras",
        "title": "Livro de Exu Sete Porteiras da Encruzilhada",
        "entity": "Exu Sete Porteiras da Encruzilhada",
        "greeting": "Laroiê, Exu Sete Porteiras!",
        "intro": "Ele guarda os sete limites entre o mundo dos homens e o mundo dos mistérios. Nenhuma passagem existe sem a sua vontade, nenhum destino se cumpre sem que ele abra ou feche a porteira. Seu número é o sete — o número da completude, da lei e da proteção absoluta.",
        "chapters": [
          {
            "num": 1,
            "verses": [
              "Porteira que eu guardo, nenhum mal atravessa sem minha permissão.",
              "As chaves do seu sucesso estão na mão de quem tem coragem de girar a maçaneta.",
              "Não peça caminho aberto se você tem medo de andar no escuro.",
              "Eu sou o dono da entrada e o senhor da saída; respeito é o que mantém a porta aberta.",
              "Muitos batem à porta, mas poucos sabem o que fazer quando ela se abre.",
              "Sete vezes eu te caio, sete vezes eu te levanto, se você for justo.",
              "Cuidado com o que você deixa entrar na sua casa e no seu pensamento.",
              "A vida é feita de ciclos, e eu sou o guardião que encerra um para começar outro.",
              "Minha porteira não tem tranca para quem vem com a verdade.",
              "Onde o mundo coloca obstáculos, eu coloco uma passagem.",
              "Quem me deve, se esconde; quem eu protejo, caminha de cabeça erguida.",
              "A encruzilhada é o mapa, e a porteira é o destino.",
              "Não confunda minha paciência com falta de vigília.",
              "Fechei as portas para a sua dor, agora cabe a você abrir as janelas para a alegria.",
              "Sete chaves eu carrego: uma para cada erro que você não deve repetir.",
              "O mundo gira, a porteira balança, mas eu não saio do meu posto.",
              "Quem passa por mim aprende que o destino é uma escolha diária.",
              "Sou o limite entre o seu ontem e o seu amanhã.",
              "Muitas vezes, fechar uma porta é o maior ato de amor próprio.",
              "Bata com fé, que a porteira de Sete Porteiras nunca emperra para o bem.",
            ]
          }
        ]
      },
      {
        "id": "marabo",
        "title": "Livro de Exu Marabô",
        "entity": "Exu Marabô",
        "greeting": "Laroiê, Exu Marabô!",
        "intro": "Senhor de porte elegante e palavra afiada, Marabô é o diplomata das encruzilhadas. Carrega no charuto a fumaça do destino e nos olhos a sentença de quem ousou desafiar a lei. Sua elegância é a armadilha dos tolos; sua execução, o despertar dos justos.",
        "chapters": [
          {
            "num": 1,
            "verses": [
              "Não é hora nem momento.",
              "A elegância de um Exu está no peso da sua palavra.",
              "Bebo do melhor marafo para limpar as piores intenções.",
              "Marabô não manda recado, ele executa a sentença.",
              "O vento que sopra a meu favor é o mesmo que derruba quem me deve.",
              "Sou o senhor dos ares e das profundezas; nada escapa ao meu olhar.",
              "A fumaça do meu charuto desenha o destino de quem tem fé.",
              "Não me peça o que você não tem coragem de sustentar.",
              "A educação é a arma mais afiada de um cavaleiro das trevas.",
              "Limpo a sua aura com o dendê fervendo, para que a inveja não grude.",
              "Marabô é lei, Marabô é ordem, Marabô é o senhor do meu destino.",
              "O respeito é a base de qualquer oferenda.",
              "Não se engane com meu porte de lorde, sou Exu na terra e no inferno.",
              "Onde Marabô pisa, o chão estremece e a mentira se cala.",
              "Sou a força que corta o mal pela raiz, sem deixar rastro.",
              "A sabedoria vem com o tempo, a proteção vem com a lealdade.",
              "Quem planta espinhos não pode caminhar descalço no meu terreiro.",
              "A capa de Marabô cobre o justo e expõe o traidor.",
              "Sou o diplomata das encruzilhadas, resolvo na conversa o que outros resolvem na guerra.",
              "A luz que eu carrego não cega, ela ilumina o erro para que haja acerto.",
            ]
          }
        ]
      },
      {
        "id": "sete-encruzilhadas",
        "title": "Livro de Exu Sete Encruzilhadas",
        "entity": "Exu Sete Encruzilhadas",
        "greeting": "Laroiê, Exu Sete Encruzilhadas!",
        "intro": "Senhor de todas as direções, guardião de todos os destinos possíveis. Onde os outros veem o fim do caminho, ele vê sete portas. Sua sabedoria não está em escolher por você, mas em mostrar o que cada escolha carrega consigo — o peso, a glória e as consequências.",
        "chapters": [
          {
            "num": 1,
            "verses": [
              "Sou o senhor das sete direções e o guardião de todas as estradas que você pode escolher.",
              "Onde você vê uma encruzilhada, eu vejo sete soluções possíveis para o seu destino.",
              "Quem passa pelas sete encruzilhadas aprende que o destino é feito de escolhas.",
              "Não tome uma decisão sem me consultar; eu conheço o final de cada caminho.",
              "Minha capa protege os justos e expõe a mentira de quem quer te enganar.",
              "Sete vezes eu te protejo, sete vezes eu te mostro a verdade.",
              "Sou o início, o meio e o fim da encruzilhada que te leva ao sucesso.",
              "Onde os caminhos se cruzam, ali eu firmo a minha lei e a minha proteção.",
              "Não tenha medo de escolher, desde que venha com o coração limpo.",
              "A encruzilhada é o mapa da sua vida, e eu sou o guia que te orienta.",
              "O mal que vem dos quatro cantos, eu travo no centro da encruzilhada.",
              "Sete chaves eu carrego, mas a mais importante é a da sua consciência.",
              "Sou o mestre do tempo e do espaço; onde você estiver, eu estarei na frente.",
              "A sorte é como a encruzilhada: pode ir para qualquer lado se você souber dirigir.",
              "Quem tem Sete Encruzilhadas ao seu lado, nunca fica sem saída.",
              "As demandas que chegam de longe morrem antes de cruzar o meu ponto.",
              "Sou o equilíbrio que organiza os ventos, as águas, a terra e o fogo.",
              "A encruzilhada não fecha caminhos, ela te ensina para onde olhar.",
              "Minha gargalhada abre os nós que prendem o seu progresso.",
              "Exu Sete Encruzilhadas é o senhor do seu passo e o guardião da sua vitória.",
            ]
          }
        ]
      },
      {
        "id": "tranca-ruas",
        "title": "Livro de Seu Tranca Ruas das Almas",
        "entity": "Seu Tranca Ruas das Almas",
        "greeting": "Laroiê, Seu Tranca Ruas das Almas!",
        "intro": "Da calunga ao cruzeiro, da rua ao portal das almas, Tranca Ruas das Almas é o guardião dos dois mundos. Seu silêncio é mais aterrador que qualquer grito; sua presença, mais poderosa que qualquer armamento. Onde ele trava, não há força humana que desbloqueie.",
        "chapters": [
          {
            "num": 1,
            "verses": [
              "Tranquei o mal para que ele não te ache, mas não destranquei sua preguiça.",
              "Sou o senhor do cadeado e o mestre da chave.",
              "Nas almas eu busco a paz, na rua eu busco a ordem.",
              "Quem caminha comigo não tropeça na sombra do inimigo.",
              "O silêncio é a minha maior resposta para quem grita sem razão.",
              "Tranca Ruas não dorme, ele apenas observa quem merece passar.",
              "O mal só entra onde encontra porta aberta pela falta de caráter.",
              "Capa preta para proteger, guia no pescoço para vencer.",
              "Não tente enganar quem conhece todos os atalhos da escuridão.",
              "Onde houver desordem, eu serei o freio.",
              "Eu tranco o seu caminho para te salvar de um abismo que você não vê.",
              "Justiça se faz com silêncio e tempo, não com gritos e pressa.",
              "O cemitério é minha morada, mas o mundo é meu campo de batalha.",
              "As almas clamam, e eu sou a voz que traz o equilíbrio.",
              "Tranquei a língua do seu inimigo para que o feitiço dele morra na boca.",
              "Quem tem Tranca Ruas na frente, não teme quem vem por trás.",
              "A escuridão só assusta quem não tem luz própria.",
              "Sou o guardião dos segredos que a noite insiste em esconder.",
              "Se eu fechar a rua, não há santo que abra sem minha vontade.",
              "O cadeado da alma só se abre com a chave do perdão.",
            ]
          }
        ]
      },
      {
        "id": "miguel",
        "title": "Livro de Exu Miguel",
        "entity": "Exu Miguel",
        "greeting": "Laroiê, Exu Miguel!",
        "intro": "Carrega um nome de príncipe e a força de um guerreiro das sombras. Exu Miguel é a lei encarnada nas encruzilhadas — sem dois pesos, sem duas medidas. Sua espada não corta carne, mas atravessa a maldade como raio atravessa o céu. Onde ele está, a hipocrisia não respira.",
        "chapters": [
          {
            "num": 1,
            "verses": [
              "Carrego o nome de um príncipe e a força de um guerreiro das sombras.",
              "A espada que eu empunho não corta a carne, corta a maldade que corrói o espírito.",
              "Justiça não se pede com choro, se conquista com retidão.",
              "Sou o sentinela que não dorme enquanto o justo corre perigo.",
              "Onde houver desordem, eu serei o freio; onde houver mentira, eu serei o espelho.",
              "Não tente barganhar com a Lei; Miguel executa o que o Alto determinou.",
              "Minha capa é o escudo de quem não tem voz diante dos poderosos.",
              "Caminho no umbral para resgatar quem se perdeu, mas não tolero quem escolheu a sombra por maldade.",
              "A luz que eu trago queima a hipocrisia.",
              "Sou o equilíbrio entre a misericórdia e a severidade.",
              "Miguel não tem dois pesos nem duas medidas: o erro é erro, não importa quem o cometa.",
              "Minha proteção é um círculo de fogo que nenhum feitiço atravessa.",
              "Honra, lealdade e fé: os três pilares que sustentam o meu ponto.",
              "Quem usa o meu nome para o mal, conhecerá o peso do meu silêncio.",
              "Sou o diplomata entre os reinos, resolvendo na lei o que a fúria não consegue.",
              "A paciência de Miguel é longa, mas o golpe é fatal.",
              "Não tema os demônios de fora, vença os que moram dentro de você.",
              "Sou a autoridade que coloca o caos em fileira.",
              "Limpo os caminhos para a luz passar, retirando os entulhos do ego humano.",
              "Exu Miguel é o braço forte da justiça nas encruzilhadas da vida.",
            ]
          }
        ]
      },
    ]
  },
  {
    "title": "PARTE II",
    "subtitle": "A Operação e a Execução",
    "epigraph": "O pensamento é o feitiço, a palavra é a oferenda, a ação é o ritual. Exu executa o que o homem tem coragem de pedir.",
    "books": [
      {
        "id": "tiriri",
        "title": "Livro de Exu Tiriri",
        "entity": "Exu Tiriri",
        "greeting": "Laroiê, Exu Tiriri!",
        "intro": "Rápido como o bote da serpente, certeiro como o raio que não avisa. Tiriri não é de conversa longa nem de promessa vaga. Ele lê a intenção antes que a boca se abra e executa antes que o inimigo perceba. Sua vidência é sua maior arma; sua rapidez, o seu escudo.",
        "chapters": [{"num": 1, "verses": [
          "Eu vejo o que os seus olhos tentam esconder de si mesmo.",
          "Tiriri não é de conversa fiada; se eu disse que vou fazer, está feito.",
          "Sou o eco da verdade no meio da mentira.",
          "Quem me chama com fé, me encontra na primeira encruzilhada.",
          "Quebro a sua demanda com a mesma facilidade que você respira.",
          "A justiça de Tiriri é rápida como o bote da serpente.",
          "Não adianta esconder a intenção; eu leio o seu coração antes de você falar.",
          "Sou o mensageiro que traz a notícia que você precisa, não a que você quer.",
          "Tiriri na frente, o mal se afasta e o caminho se apresenta.",
          "Minha luz é o farol que guia quem se perdeu na própria soberba.",
          "Quem deve a Tiriri, paga na hora da colheita.",
          "Sou o guarda da sua palavra; sustente o que diz ou não diga nada.",
          "Onde houver feitiço escondido, meu olhar o revelará.",
          "Não me peça vingança, me peça justiça e observe o que acontece.",
          "Minha gargalhada corta o ar para avisar que a verdade chegou.",
          "Tiriri é fogo, é terra, é a força que não retrocede.",
          "Eu ando na frente para você não cair na armadilha alheia.",
          "A lealdade é a moeda que eu aceito no meu terreiro.",
          "Muitos têm medo do meu nome, mas só os culpados têm razão para isso.",
          "Laroiê Tiriri, o dono da vidência e o senhor da rapidez.",
        ]}]
      },
      {
        "id": "capa-preta",
        "title": "Livro de Exu Capa Preta",
        "entity": "Exu Capa Preta",
        "greeting": "Laroiê, Exu Capa Preta!",
        "intro": "Sob o manto negro, os segredos do universo encontram proteção. Exu Capa Preta trabalha invisível — ninguém o vê chegar, ninguém o vê partir. Sua força está no mistério e no sigilo; sua capa não é apenas tecido, é o escudo da alma contra tudo que rasteja no escuro.",
        "chapters": [{"num": 1, "verses": [
          "Debaixo da minha capa, o justo se esconde e o mal se perde.",
          "O que eu cubro com meu manto, nenhum olho humano consegue devassar.",
          "Sou o senhor do mistério, o guardião do que deve permanecer em segredo.",
          "Minha capa não serve apenas para vestir, serve para abafar o grito da injustiça.",
          "Cuidado com o que você faz no escuro; para mim, a noite é clara como o dia.",
          "Sou o silêncio que precede o golpe e a escuridão que cega o traidor.",
          "Quem tem a proteção da minha capa, caminha invisível no meio do exército inimigo.",
          "A verdadeira força não se mostra, se guarda para o momento do xeque-mate.",
          "Trabalho nas sombras para que a sua luz possa brilhar sem ser atacada.",
          "Minha capa é feita de respeito, lealdade e o aço das minhas batalhas.",
          "Não tente descobrir o que eu escondo; o mistério é o que mantém o meu poder.",
          "Capa Preta não avisa: ele chega, resolve e se retira sem deixar rastro.",
          "Onde eu estendo o meu manto, o feitiço do outro não encontra morada.",
          "Sou o mestre das artes ocultas e o vigia das passagens proibidas.",
          "A escuridão só assusta quem não conhece o dono da noite.",
          "Minha presença é sentida pelo calafrio de quem sabe que está errado.",
          "Protejo os segredos dos meus filhos como se fossem o meu maior tesouro.",
          "Capa Preta é lei nas trevas e ordem no caos.",
          "Não se engane com o meu porte sério; minha justiça é implacável e silenciosa.",
          "Debaixo da minha capa, a sua dor descansa até que eu a transforme em vitória.",
        ]}]
      },
      {
        "id": "veludo",
        "title": "Livro de Exu Veludo",
        "entity": "Exu Veludo",
        "greeting": "Laroiê, Exu Veludo!",
        "intro": "Elegância é poder. Exu Veludo conhece os salões e as valas com a mesma postura de rei. Não grita, não corre, não ameaça em vão. Sua estratégia é a sutileza; sua arma, as palavras que abre portas onde o machado só encontraria resistência. Mão de ferro em luva de seda.",
        "chapters": [{"num": 1, "verses": [
          "Sou fino no trato e certeiro no golpe; a elegância é o meu melhor disfarce.",
          "Muitos tentam me imitar, mas o brilho do veludo não se encontra em qualquer esquina.",
          "Resolvo na conversa o que outros levam uma vida para resolver na briga.",
          "Meu passo é macio para não acordar o inimigo antes da hora.",
          "Bebo do melhor vinho para celebrar a vitória de quem sabe esperar o tempo certo.",
          "A educação é a armadilha onde os ignorantes caem com prazer.",
          "Não confunda minha gentileza com fraqueza; o veludo esconde o aço.",
          "Sou o senhor das palavras que abrem portas trancadas pelo orgulho.",
          "A beleza da estratégia está em vencer sem precisar derramar sangue.",
          "Caminho nos salões e nas valas com a mesma postura de rei.",
          "Quem me tem como aliado, tem um mestre na arte da persuasão.",
          "A vida é um banquete; saiba sentar-se à mesa antes de querer mandar nela.",
          "Onde o barulho falha, o meu sussurro faz milagres.",
          "Sou a suavidade que envolve o problema até sufocá-lo.",
          "Veludo é o toque que acalma o aflito e gela a espinha do traidor.",
          "Não me peça o impossível, peça o caminho para torná-lo real.",
          "O mistério de Veludo é saber o segredo de todos sem nunca revelar o seu.",
          "Ouro brilha, mas a classe de um Exu é o que impõe respeito.",
          "Sou a mão de ferro em luva de seda.",
          "Veludo não se discute, se admira de longe e se respeita de perto.",
        ]}]
      },
      {
        "id": "gira-mundo",
        "title": "Livro de Exu Gira Mundo",
        "entity": "Exu Gira Mundo",
        "greeting": "Laroiê, Exu Gira Mundo!",
        "intro": "Tudo gira — a roda da fortuna, o ciclo das eras, o destino dos homens. Exu Gira Mundo é o senhor desse movimento eterno. Ele não empurra: ele incita o giro. Não derruba: retira o que estava sustentado pela mentira. O que é de direito, volta. O que foi plantado com dolo, retorna multiplicado.",
        "chapters": [{"num": 1, "verses": [
          "O mundo gira, as máscaras caem e eu fico aqui, apenas observando o tombo dos arrogantes.",
          "Eu sou o eixo que faz a roda da sua vida girar quando tudo parece parado.",
          "Não reclame da volta que o mundo deu; agradeça por eu ter te tirado do lugar que te fazia mal.",
          "Para onde você vai, eu já fui e já voltei sete vezes.",
          "Sou o senhor dos ventos que mudam as direções e das estradas que nunca terminam.",
          "Quem planta vento na segunda, colhe tempestade na terça com a minha ajuda.",
          "O que hoje está em cima, amanhã estará embaixo; a vida é um ciclo e eu sou o mestre dele.",
          "Não tente parar o mundo, aprenda a girar com ele sem perder o equilíbrio.",
          "Minha missão é colocar cada coisa no seu devido lugar, custe o que custar.",
          "Sou o movimento que gera a vida e a inércia que precede a morte.",
          "Gira Mundo não corre, ele apenas faz o caminho chegar mais rápido até você.",
          "A cada volta que eu dou, um nó se desfaz e uma verdade aparece.",
          "Sou o dono das oportunidades que você deixou passar por medo de girar.",
          "A sorte é uma roda que eu impulsiono com a força da sua fé.",
          "Onde houver estagnação, eu trarei o furacão da mudança.",
          "Muitos temem o giro, mas só quem gira conhece as paisagens do mundo inteiro.",
          "Cuidado com o que você deseja; o mundo gira rápido e o retorno é certeiro.",
          "Sou o tempo que não para e o espaço que se renova a cada segundo.",
          "Gira Mundo, gira a sorte, gira a vida e afasta a morte.",
          "Minha lei é o movimento; parado, nem a água fica limpa.",
        ]}]
      },
      {
        "id": "arranca-toco",
        "title": "Livro de Exu Arranca Toco",
        "entity": "Exu Arranca Toco",
        "greeting": "Laroiê, Exu Arranca Toco!",
        "intro": "O obstáculo que o tempo não removeu, ele arranca pela raiz. Exu Arranca Toco não negocia com o que precisa ser eliminado — age com a força da terra, o peso do machado e a precisão de quem sabe exatamente onde cortar para que a cura comece.",
        "chapters": [{"num": 1, "verses": [
          "Onde há raiz de mal que o tempo não tirou, eu uso o meu machado.",
          "Arranco o obstáculo do seu caminho, não importa o tamanho da teimosia dele.",
          "Sou o senhor das florestas mais escuras e das raízes que insistem em não ceder.",
          "Não há tempestade que derrube quem tem Arranca Toco como protetor.",
          "Meu trabalho é cortar pela raiz o que tenta te impedir de crescer.",
          "Se o seu problema parece uma árvore morta, eu sou o vento que a joga no chão.",
          "Arranco as amarras do passado para que você possa caminhar com leveza.",
          "Não peça um caminho fácil, peça a força para vencer o que vier.",
          "Sou a força da terra, o aço das matas e o freio da injustiça.",
          "A mentira do teu inimigo é como um tronco podre diante da minha força.",
          "Quem me tem na frente, não teme o peso da responsabilidade.",
          "Abro a passagem onde antes só havia mato fechado.",
          "Onde os outros recuam, eu entro com o machado na mão e a fé no peito.",
          "A limpeza que eu faço é pesada, mas o resultado é definitivo.",
          "A sua coragem é o meu combustível para arrancar o que te faz mal.",
          "Sou o gigante que vigia a porteira e protege a casa.",
          "Cortei o mal pela raiz, agora o seu caminho está limpo para a vitória.",
          "O machado de Arranca Toco não fere o justo, ele apenas liberta.",
          "Muitos tentam te prender ao chão, mas eu dou a força para você voar.",
          "Exu Arranca Toco é a lei, a ordem e o impulso para o seu novo ciclo.",
        ]}]
      },
      {
        "id": "mare",
        "title": "Livro de Exu Maré",
        "entity": "Exu Maré",
        "greeting": "Laroiê, Exu Maré!",
        "intro": "Como o mar, ele não se pode segurar — avança e recua no ritmo que só ele conhece. Exu Maré trabalha com a persistência das águas, que não batem uma vez na pedra, mas a moldam durante séculos. Sua limpeza é total: sal, espuma e mistério das profundezas.",
        "chapters": [{"num": 1, "verses": [
          "O que a onda traz, a onda leva; aprenda a não segurar o que o destino quer carregar.",
          "Sou como o mar: calmo para quem sabe navegar, mas implacável para quem me desafia.",
          "Minha força não está no golpe, está na insistência da água contra a pedra.",
          "Limpo a sua alma com sal e espuma, para que nenhuma demanda consiga grudar.",
          "Não se engane com a calmaria da superfície; as maiores verdades estão no fundo do oceano.",
          "Sou o senhor das marés: eu sei a hora exata de avançar e o momento sagrado de recuar.",
          "Quem me deve, paga na areia; quem eu protejo, descansa no porto seguro.",
          "A vida é um fluxo constante; quem tenta parar o tempo acaba afogado na própria ansiedade.",
          "Mergulho no seu problema para trazer a solução que você não consegue enxergar.",
          "Sou o mistério do horizonte, onde o céu e o mar se tornam uma coisa só.",
          "O lixo que jogam em mim, eu devolvo para a praia; o mundo faz o mesmo com o que você planta.",
          "Minha gargalhada é o barulho das ondas quebrando no rochedo da injustiça.",
          "Não peça para a tempestade parar, peça para eu te ensinar a ser o capitão do seu barco.",
          "A areia apaga as pegadas, mas eu guardo a memória de cada passo que você deu.",
          "Sou a força que puxa o mal para as profundezas e traz a renovação na crista da onda.",
          "Maré cheia de axé, maré vazia de inveja.",
          "O sal que queima a ferida é o mesmo que preserva a alma da podridão.",
          "Navegar é preciso, mas respeitar o dono do mar é fundamental.",
          "Sou o equilíbrio entre a força do fundo e a beleza da beira.",
          "Deixe que as águas de Maré levem o que não te pertence mais.",
        ]}]
      },
      {
        "id": "tranca-tudo",
        "title": "Livro de Exu Tranca Tudo",
        "entity": "Exu Tranca Tudo",
        "greeting": "Laroiê, Exu Tranca Tudo!",
        "intro": "Exu Tranca Tudo é o mestre das chaves e dos cadeados — tanto os de ferro quanto os invisíveis. Sua missão é garantir que nenhuma intenção maligna encontre passagem, nenhuma demanda alheia encontre morada. O que ele fecha, permanece fechado até que a justiça decida abrir.",
        "chapters": [{"num": 1, "verses": [
          "Tranco o mal, tranco a inveja, tranco o caminho de quem quer te ver cair.",
          "Onde há perigo, eu coloco a minha chave e fecho a porta para o inimigo.",
          "Não há tranca que resista à força da fé de quem confia no meu trabalho.",
          "Sou o homem trabalhador que guarda as sete chaves do destino.",
          "Se eu trancar tudo, ninguém passa sem a minha permissão.",
          "Abro os caminhos para o nosso povo, mas fecho as portas para quem vem com dolo.",
          "Onde há confusão, eu coloco a ordem e o respeito.",
          "Minhas chaves abrem os segredos que o mundo insiste em esconder.",
          "Tranco a boca do invejoso e os passos do caluniador.",
          "Quem caminha com Tranca Tudo não tropeça na sombra da falsidade.",
          "Sou a sentinela que protege o ambiente para que o bem possa atuar.",
          "Minhas chaves são forjadas no aço da justiça e da lealdade.",
          "Onde os outros deixam portas abertas ao vento, eu coloco o meu cadeado.",
          "O trabalho de Exu é para quem tem fé, pé no chão e coração aberto.",
          "Eu tranco o seu passado de dor para que você possa entrar no futuro.",
          "A chave que fecha o seu sofrimento é a mesma que abre a sua vitória.",
          "Minha gargalhada espanta as sombras e limpa a estrada.",
          "Sou o mestre do ponto miúdo e do trabalho certeiro.",
          "Nenhuma demanda resiste à força de Exu Tranca Tudo.",
          "Laroiê, Exu Tranca Tudo! Dono dos caminhos e senhor da segurança.",
        ]}]
      },
    ]
  },
  {
    "title": "PARTE III",
    "subtitle": "O Poder Decisor",
    "epigraph": "A Pombagira não pede. A Pombagira determina. E o que ela determina, o universo obedece.",
    "books": [
      {
        "id": "maria-padilha",
        "title": "Livro de Maria Padilha",
        "entity": "Maria Padilha",
        "greeting": "Laroyê, Maria Padilha!",
        "intro": "Rainha das encruzilhadas da noite, dona dos segredos do amor e da sedução. Maria Padilha não aceita meias-palavras nem ofertas incompletas. Chegou para reinar, não para servir. O poder que ela carrega é ancestral, irreversível e absoluto — e quem a subestima aprende na dor.",
        "chapters": [{"num": 1, "verses": [
          "Não sou mulher de aceitar migalhas; ou você me dá tudo, ou não me dá nada.",
          "O feitiço que eu faço é com o olhar; o resto é só ferramenta.",
          "Quem mexe com Padilha sabe que o fogo que aquece é o mesmo que consome.",
          "Rainha não pede licença, Rainha ocupa o lugar que é dela por direito.",
          "Meu salto alto pisa em cima da língua de quem fala mal de mim.",
          "Onde eu chego, a noite se ilumina e o inimigo se retira.",
          "Não me chame se você não aguenta a verdade que eu vou te dizer.",
          "Perfume de mulher, força de guerreira e sabedoria de feiticeira.",
          "Eu já vivi mil vidas e conheço cada truque que você tenta usar.",
          "A rosa que eu carrego tem perfume para os amigos e espinhos para os traidores.",
          "Sete saias eu visto para esconder os segredos que o mundo não pode saber.",
          "Padilha não dorme, ela vigia o sono de quem ela ama e o desespero de quem a deve.",
          "O amor é uma arma, e eu sou a melhor atiradora que existe.",
          "Cuidado com o que você deseja na encruzilhada; eu costumo realizar.",
          "Sou a dona do cabaré da vida, onde cada um paga o preço do que consome.",
          "Não se cura uma ferida com o que a causou; deixe que eu traga o remédio.",
          "Minha taça transborda o vinho da vitória para quem tem coragem.",
          "Gargalho para espantar o mal e para avisar que a Rainha chegou.",
          "A beleza passa, mas o poder de uma Pombagira é eterno.",
          "Se você quer o trono, aprenda primeiro a servir a sua própria verdade.",
        ]}]
      },
      {
        "id": "maria-mulambo",
        "title": "Livro de Maria Mulambo",
        "entity": "Maria Mulambo",
        "greeting": "Laroyê, Maria Mulambo!",
        "intro": "Do lixo ao luxo — essa é a trajetória de Maria Mulambo. Ela colheu o que o mundo descartou e fez coroa. Sua força está na transformação da dor em poder, do abandono em reinado. Quem a menospreza pela aparência nunca entendeu que a pobreza de espírito é a única miséria real.",
        "chapters": [{"num": 1, "verses": [
          "Do lixo eu vim, no luxo eu vivo e para o lixo eu mando quem me despreza.",
          "Não olhe para os meus trapos, olhe para a coroa que brilha na minha alma.",
          "Quem me viu chorar, vai me ver gargalhar em cima da sua derrota.",
          "Sou a prova de que o sofrimento é apenas o adubo para a força.",
          "Mulambo não é sujeira, é o desapego de quem já teve tudo e descobriu o essencial.",
          "Limpo a sua alma com a mesma mão que recolhe os restos do seu passado.",
          "Muitos querem a minha beleza, mas poucos aguentariam o peso da minha história.",
          "A verdadeira riqueza não se carrega no bolso, se carrega no brilho do olhar.",
          "Fui rainha, fui escrava, mas em todas as vidas eu fui Maria.",
          "Não confunda minha simplicidade com falta de poder.",
          "Eu transformo a dor em força e a lágrima em feitiço.",
          "Ouro nenhum compra a lealdade de uma Mulambo.",
          "Cuidado com quem você pisa hoje; amanhã eu posso ser a única mão estendida.",
          "Minha vassoura varre o que não presta e traz o que é de merecimento.",
          "Sou a senhora do lixo, onde escondo os tesouros que ninguém sabe valorizar.",
          "A pobreza é de espírito; o resto é apenas falta de oportunidade.",
          "Mulambo caminha descalça para sentir o pulsar da terra que a acolheu.",
          "Não me peça luxo, peça para eu tirar a sujeira que impede você de crescer.",
          "Onde o mundo jogou fora, eu fui lá e fiz morada.",
          "Gargalho da arrogância, pois sei que no fim, todos voltam para o mesmo pó.",
        ]}]
      },
      {
        "id": "maria-quiteria",
        "title": "Livro de Maria Quitéria",
        "entity": "Maria Quitéria",
        "greeting": "Laroyê, Maria Quitéria!",
        "intro": "Trocou o vestido pela farda e nunca olhou para trás. Maria Quitéria é a guerreira que não pede permissão para entrar em batalha — ela já está na frente antes mesmo do inimigo perceber o perigo. Sua disciplina é absoluta, sua coragem, um farol para quem perdeu a direção.",
        "chapters": [{"num": 1, "verses": [
          "Não nasci para ser sombra de homem, nasci para ser a luz que guia o meu exército.",
          "Troquei o vestido pela farda e a submissão pela espada.",
          "Onde eu piso, a traição não cria raiz.",
          "Minha guerra é silenciosa, mas minha vitória faz barulho.",
          "Cuidado com o brilho da minha lâmina; ela corta o mal antes dele te tocar.",
          "Sou soldado de frente, não fico na retaguarda esperando o perigo passar.",
          "Justiça se faz com coragem, não com desculpas.",
          "Se você quer paz, prepare-se para a guerra comigo ao seu lado.",
          "Não me peça para ter pena de quem planejou a sua queda.",
          "Minha estratégia é a paciência; meu golpe é a precisão.",
          "Quitéria não brinca de lutar, ela entra em campo para vencer.",
          "A disciplina é a chave que abre as portas que a sorte não consegue.",
          "Muitas falam, poucas sustentam o peso de uma farda de guerra.",
          "Sou a sentinela da sua vida; durma em paz enquanto eu vigio.",
          "O inimigo cai pelo próprio erro, eu apenas dou o empurrão final.",
          "Honra não se compra, se constrói com sangue, suor e fé.",
          "Quem tem Maria Quitéria na frente, não teme emboscada por trás.",
          "Sou a força que levanta o caído e o braço que derruba o arrogante.",
          "Minha missão é proteger o justo e desarmar o traidor.",
          "No meu quartel, a única regra é a lealdade.",
        ]}]
      },
      {
        "id": "maria-mandinga",
        "title": "Livro de Maria da Mandinga",
        "entity": "Maria da Mandinga",
        "greeting": "Laroyê, Maria da Mandinga!",
        "intro": "Mandinga não se aprende em livro — se sente no osso, se herda do sangue, se firma na raiz da terra. Maria da Mandinga é a feiticeira mais antiga, a que conhece o nome de cada erva e o segredo de cada nó. Seus caldeirões fervem verdades que a ciência ainda não encontrou palavras para descrever.",
        "chapters": [{"num": 1, "verses": [
          "Mandinga não se explica, mandinga se sente no pé e no coração.",
          "Meu caldeirão ferve o que a sua boca não tem coragem de dizer.",
          "Para cada nó que deram na sua vida, eu tenho sete formas de desatar.",
          "Não chame de sorte o que eu conquistei com rezo e fundamento.",
          "A força da minha palavra atravessa paredes e quebra correntes.",
          "Sou a dona dos segredos que a lua conta para a noite.",
          "Erva que cura, erva que mata; eu sei o tempo certo de cada uma.",
          "Mandingueira velha não se assusta com sombra de assombração.",
          "O feitiço volta para quem mandou se ele encontrar o meu muro de proteção.",
          "Minha saia roda o mundo, mas meu pé está fincado no mistério.",
          "Quem me deve paga com o sono, quem me tem ganha o destino.",
          "Cuidado com o que você joga no vento; eu sou o vento que traz de volta.",
          "Pó de estrada, cinza de fogueira e a fé de quem nunca se entrega.",
          "Não mexe com quem sabe silenciar o mal com um único olhar.",
          "Minha magia é raiz, é terra, é o que o tempo não consegue apagar.",
          "Sou a senhora das mirongas, onde a lógica dos homens se perde.",
          "Fiz um pacto com a verdade e ela nunca me deixou na mão.",
          "Mandinga de verdade se faz na calada, sem plateia e sem vaidade.",
          "Onde o nó é cego, eu sou a faca que devolve a luz.",
          "Maria da Mandinga é o eco do terreiro nas entranhas da alma.",
        ]}]
      },
      {
        "id": "rosa-caveira",
        "title": "Livro de Rosa Caveira",
        "entity": "Rosa Caveira",
        "greeting": "Laroyê, Rosa Caveira!",
        "intro": "Ela une o perfume da rosa à frieza da calunga. Rosa Caveira é a Pombagira que habita o limiar entre a vida e a morte, colhendo as verdades que só emergem quando a carne já não importa mais. Sua beleza não é física — é a beleza de quem atravessou o fundo do abismo e voltou com poder.",
        "chapters": [{"num": 1, "verses": [
          "A vida é como uma rosa: bela para quem sabe cuidar e cheia de espinhos para quem tenta arrancar.",
          "No meu jardim de ossos, as flores nascem da dor transmutada em poder.",
          "Quem me vê como esqueleto não conhece a beleza da minha alma guerreira.",
          "Sou o equilíbrio entre a delicadeza do perfume e a frieza da calunga.",
          "Minha gargalhada é o aviso de que a justiça da morte chegou para organizar a vida.",
          "Não peça rosas se você não aguenta o peso dos espinhos que elas carregam.",
          "Sou a senhora que caminha entre os mundos, colhendo verdades e enterrando mentiras.",
          "Rosa Caveira não aceita desculpas, ela aceita mudança e merecimento.",
          "Onde eu coloco a minha mão, o feitiço do inimigo vira pó de estrada.",
          "Sou a prova de que a beleza sobrevive até no mais árido dos terrenos.",
        ]}]
      },
      {
        "id": "maria-bonita",
        "title": "Livro de Maria Bonita",
        "entity": "Maria Bonita",
        "greeting": "Laroyê, Maria Bonita!",
        "intro": "Do sertão nordestino para a eternidade das encruzilhadas — Maria Bonita é a rainha do cangaço, a mulher que escolheu a liberdade quando o mundo só oferecia correntes. Sua justiça é seca e direta como o sol do sertão. Sua lealdade, mais valiosa que ouro em tempos de seca.",
        "chapters": [{"num": 1, "verses": [
          "Sou a rainha do cangaço e a dona do meu próprio destino.",
          "O sol do sertão queimou minha pele, mas temperou o meu aço.",
          "Não me curvo para rei, imagine para quem se acha melhor que eu.",
          "Minha justiça é seca e direta, como o chão do meu nordeste.",
          "Mulher de fibra não chora por pouco, faz do pranto munição.",
          "Cangaceira não foge da luta, ela escolhe o melhor lugar para atirar.",
          "Quem tem Maria Bonita ao lado, tem a força da terra rachada.",
          "O brilho do meu punhal é a última coisa que o traidor vê.",
          "Coragem é o meu perfume, liberdade é a minha morada.",
          "Não me venha com mansidão se o mundo te trata com espinhos.",
          "No meio da caatinga, quem não é esperto vira banquete de carcará.",
          "Sou o grito de liberdade de quem nunca aceitou ser escravo.",
          "Minha lei é o respeito; minha punição é o esquecimento.",
          "Galo não canta no meu terreiro se eu não der a ordem.",
          "A vida é um deserto, mas eu conheço todos os caminhos para a água.",
          "Beleza e perigo caminham juntos na ponta da minha adaga.",
          "Protejo os meus com dentes e unhas, como leoa no mato.",
          "O medo é um luxo que eu não carrego na minha bornal.",
          "Maria Bonita não é só nome, é a honra de quem sabe lutar.",
          "Quem caminha comigo aprende que a dignidade vale mais que a vida.",
        ]}]
      },
    ]
  },
  {
    "title": "PARTE IV",
    "subtitle": "Transmutação e Limpeza de Fundo",
    "epigraph": "O que não pode ser curado pela luz, é curado pela escuridão que pertence ao mesmo Deus.",
    "books": [
      {
        "id": "caveira",
        "title": "Livro de Exu Caveira & Tata Caveira",
        "entity": "Exu Caveira & Tata Caveira",
        "greeting": "Laroiê, Exu Caveira!",
        "intro": "No reino onde a carne não entra, Exu Caveira e Tata Caveira são os senhores absolutos. A morte não é o seu domínio por acaso — eles a conhecem como ninguém e por isso sabem o valor inestimável de cada momento de vida. Sua mensagem é simples e devastadora: vaidade é coisa de quem ainda não visitou o campo santo.",
        "chapters": [{"num": 1, "verses": [
          "No meu reino, a vaidade não tem carne; só resta a essência do que você realmente é.",
          "Eu não mato ninguém, eu apenas acompanho quem já morreu em vida.",
          "O cemitério é o meu jardim, e as almas são as flores que eu cultivo para o novo tempo.",
          "Não tema a caveira, tema o coração vivo que guarda o ódio.",
          "Eu sou o espelho: o que você vê em mim é o que você carrega por dentro.",
          "A morte não é o fim, é o momento em que eu retiro a sua máscara.",
          "Quem caminha entre túmulos aprende a valorizar cada segundo de respiração.",
          "A terra tudo come, mas o que é de espírito, nem o tempo consome.",
          "Sou a calmaria do campo santo e a tempestade na vida do injusto.",
          "Caveira não brinca, Caveira executa a lei que a carne tenta ignorar.",
          "Trabalho no silêncio, pois o barulho é coisa de quem não tem poder.",
          "A riqueza do homem termina no portão onde eu começo a mandar.",
          "Não me peça ouro, me peça sabedoria para não se perder no brilho dele.",
          "A foice que eu carrego corta o laço que te prende ao passado.",
          "Sete palmos de terra é o que nivela o rei e o mendigo.",
          "Sou o guardião do descanso eterno e o vigia do despertar espiritual.",
          "Onde o osso encontra a terra, ali eu firmo o meu ponto.",
          "A luz que eu trago vem da escuridão que você tem medo de enfrentar.",
          "Tata Caveira é o velho que sabe que a pressa é inimiga da perfeição.",
          "Respeite o chão que você pisa, pois um dia ele será o seu cobertor.",
        ]}]
      },
      {
        "id": "meia-noite",
        "title": "Livro de Exu Meia-Noite",
        "entity": "Exu Meia-Noite",
        "greeting": "Laroiê, Exu Meia-Noite!",
        "intro": "Na hora em que o dia morre e a noite nasce, é ali que Exu Meia-Noite reina. Ele é o senhor do portal entre o que foi e o que será — a hora da verdade nua, onde nenhuma máscara resiste. Suas doze badaladas não são simples sons; são golpes certeiros sobre cada obstáculo que ainda prende o espírito.",
        "chapters": [{"num": 1, "verses": [
          "Na hora em que o dia morre e a noite nasce, é ali que eu governo.",
          "Sou o dono do tempo que ninguém consegue segurar.",
          "A Meia-Noite é o momento da verdade: as máscaras caem e a alma aparece nua.",
          "Quem faz pacto com o tempo, tem o Exu Meia-Noite como testemunha.",
          "Trabalho no silêncio da hora grande, onde o mundo para e o mistério grita.",
          "Não tema a escuridão da meia-noite; tema a cegueira da alma ao meio-dia.",
          "Sou o senhor das doze badaladas: cada uma é um golpe no seu impedimento.",
          "O que você não resolveu durante o dia, eu te ajudo a enfrentar no escuro.",
          "Meia-Noite é o limite entre o que foi e o que será.",
          "Sou o vigia dos sonhos e o carrasco dos pesadelos.",
          "Meu tempo é diferente do seu; eu vejo o fim antes mesmo do começo.",
          "Nas sombras da meia-noite, eu teço o destino de quem tem coragem.",
          "Quem me chama nessa hora, não tem tempo para brincadeira.",
          "Sou o eco do sino que avisa: a justiça chegou.",
          "A luz da lua é a minha lanterna, e as estrelas são meus pontos riscados.",
          "Não tente enganar o relógio; eu sou o dono das horas.",
          "Trago a cura nas trevas para quem não a encontrou na luz.",
          "Sou o guardião do portal que só se abre quando o mundo dorme.",
          "Meia-Noite é o silêncio que ensina e a escuridão que protege.",
          "Onde o tempo para, Exu Meia-Noite começa a trabalhar.",
        ]}]
      },
      {
        "id": "lodo",
        "title": "Livro de Exu do Lodo",
        "entity": "Exu do Lodo",
        "greeting": "Laroiê, Exu do Lodo!",
        "intro": "Onde o homem vê sujeira e abandono, Exu do Lodo vê a terra úmida que gera a vida. Ele trabalha nos lugares que ninguém tem coragem de entrar, removendo o que está podre para que o que é forte possa florescer. O lodo não é fraqueza — é o fundamento onde o lótus encontra sustento.",
        "chapters": [{"num": 1, "verses": [
          "Onde você vê sujeira e estagnação, eu vejo a terra úmida que cria a vida.",
          "Sou o senhor das profundezas do mangue e do lodo que cobre os segredos do mundo.",
          "O que o homem joga fora no lodo, eu recolho, limpo e dou valor.",
          "Quem tenta afundar a minha vida, descobre que o lodo é a minha morada.",
          "Meu reino é a terra que germina: dou força para o que parece perdido.",
          "O mal que vem contra você gruda no lodo e afunda antes de te tocar.",
          "Limpo os seus caminhos usando a força da natureza que purifica.",
          "Não tenha medo da lama; é dela que o lótus tira o seu sustento.",
          "Sou a força que puxa para baixo a arrogância de quem se acha puro demais.",
          "No lodo, eu firmo o meu ponto e crio uma muralha contra a inveja.",
          "Quem pisa no meu mistério aprende que o fundo do poço é apenas um trampolim.",
          "Sou o Exu que trabalha onde os outros não têm coragem de pisar.",
          "O lodo cura a ferida do corpo e protege o espírito contra a falsidade.",
          "A superfície é ilusão; no fundo é que eu sei quem é quem.",
          "Seu inimigo tenta te atolar, mas eu transformo esse atoleiro em fundamento.",
          "Minha gargalhada ecoa nas águas paradas para espantar a maldade.",
          "Lodo é terra viva, é axé puro que alimenta os fortes.",
          "Não me peça para limpar o que você sujou; peça para eu te dar a força de carregar o seu destino.",
          "Sou a testemunha silenciosa do que a sociedade prefere esconder.",
          "Exu do Lodo não desiste de ninguém que tenha fé na sua própria história.",
        ]}]
      },
      {
        "id": "morcego",
        "title": "Livro de Exu Morcego",
        "entity": "Exu Morcego",
        "greeting": "Laroiê, Exu Morcego!",
        "intro": "Voa onde a luz não alcança e enxerga o que a claridade oculta. Exu Morcego é o guardião silencioso da noite, que trabalha sem ser visto e protege sem ser celebrado. Sua lei é cumprida no silêncio das asas abertas — e quando ele fala, é porque a sentença já foi proferida.",
        "chapters": [{"num": 1, "verses": [
          "Sou o guardião da noite, dono da sombra e do portão.",
          "Meu passo é leve, mas o meu caminhar faz o ar tremer.",
          "Não falo à toa, mas quando a minha boca se abre, a palavra é lei que ninguém desfaz.",
          "Voo na escuridão para enxergar o que a luz do dia tenta camuflar.",
          "Tua capa é lei, teu silêncio convém; quem te desafia sente o chão virar.",
          "Não gosto da claridade dos falsos, eu prefiro a verdade da escuridão.",
          "Trabalho com a caveira e na calunga, cortando a maldade pela raiz.",
          "Quando a lua aparece, abro minhas asas e protejo quem tem fé.",
          "Exu Morcego não é bom nem é mal, apenas cumpre a lei que foi ordenada.",
          "Meu escudo brilha como diamante na calada da noite.",
          "Quem chama meu nome na hora do lamento, escuta o bater das minhas asas.",
          "A noite é o meu castelo e nele não entra a agonia do mundo.",
          "Onde o sol se esconde, o meu trabalho começa.",
          "Trago o frio do sereno para congelar a língua de quem fala pelas costas.",
          "Sou a sombra que te protege e o vento que sopra o inimigo para longe.",
          "Minha sabedoria vem do silêncio de quem voa sem fazer barulho.",
          "Quem tem o Morcego como guardião caminha sob um manto de proteção absoluta.",
          "A futilidade não me alcança; só resta a força da verdade.",
          "Escuto o lamento do aflito e venho voando para trazer o axé.",
          "Laroiê, senhor da escuridão! Tua voz é trovão para quem tenta o mal.",
        ]}]
      },
    ]
  },
  {
    "title": "PARTE V",
    "subtitle": "Mediação e Fundamentos",
    "epigraph": "Fundamento é raiz. Raiz não se vê, mas sem ela, nada fica em pé.",
    "books": [
      {
        "id": "ze-pilintra",
        "title": "Livro de Zé Pilintra",
        "entity": "Zé Pilintra",
        "greeting": "Saravá, Zé Pilintra!",
        "intro": "Da lapa carioca para a eternidade das encruzilhadas, Zé Pilintra é o malandro sagrado — o que vive na fronteira entre o mundo dos espertos e o mundo dos tolos, e sempre sabe de que lado ficar. Com charme, chapéu de lado e navalha no bolso, ele ensina que a malandragem verdadeira é a arte de viver bem sem pisar em ninguém.",
        "chapters": [{"num": 1, "verses": [
          "O segredo do bom jogador não é ter as melhores cartas, mas saber a hora de blefar.",
          "Não sou dono do mundo, mas sou filho do dono e afilhado de quem manda.",
          "A lapa é meu terreiro, e a rua é minha escola de vida.",
          "Malandro que é malandro não corre atrás do ônibus, espera o próximo com um sorriso.",
          "Navalha no bolso, chapéu de lado e o coração pronto para ajudar quem merece.",
          "Se o seu problema é grande, a minha vontade de rir dele é maior.",
          "Cuidado com quem você chama de amigo na hora da mesa farta.",
          "A vida me ensinou a cair como folha e levantar como fênix.",
          "Bebo meu gole para esquecer as mágoas e acordar a coragem.",
          "A malandragem é a arte de viver bem em um mundo que quer te ver mal.",
          "Quem usa terno branco não pode se sujar com lama de inveja.",
          "O mundo dá voltas, e é nessas voltas que eu te encontro.",
          "Fé no santo, olho no bicho e o pé sempre no chão.",
          "Não cutuque o malandro com vara curta, ele conhece o caminho de volta.",
          "A humildade é a capa mais bonita que um homem pode vestir.",
          "Para quem é de fé, um passo em falso é só o começo de uma dança.",
          "Dinheiro na mão é fumaça, mas a palavra de um homem é pedra.",
          "Se a vida te der as costas, passe a mão na bunda dela e saia rindo.",
          "Eu não sou de briga, mas não fuja de mim se você estiver errado.",
          "Saúde para quem quer, sorte para quem merece e Zé Pilintra para quem tem fé.",
        ]}]
      },
      {
        "id": "pemba",
        "title": "Livro de Exu Pemba",
        "entity": "Exu Pemba",
        "greeting": "Laroiê, Exu Pemba!",
        "intro": "A Pemba é o traço que separa o sagrado do profano, o protegido do exposto. Exu Pemba é o mestre dos pontos riscados — cada linha que ele traça no chão é uma lei firmada entre o mundo visível e o invisível. Onde a Pemba toca, o fundamento se instala.",
        "chapters": [{"num": 1, "verses": [
          "Sou o Exu que risca o ponto para que o mal não ouse ultrapassar.",
          "A Pemba que eu uso é a terra sagrada que firma a energia do terreiro.",
          "Onde eu traço a linha com a Pemba, ali se faz a minha morada de proteção.",
          "Não há mistério que não se revele quando a Pemba toca o chão.",
          "A firmeza do seu espírito começa pela firmeza da sua consciência.",
          "Sou o guardião do ponto riscado e o protetor dos fundamentos da calunga.",
          "A Pemba branca limpa, a vermelha protege e a preta afasta o inimigo.",
          "O traço que eu faço une o mundo material com o mistério de cima.",
          "Minha força está na terra e no axé que sustenta o seu caminhar.",
          "Risquei meu ponto na encruzilhada para que a sua fé seja inabalável.",
          "Quem conhece o valor da Pemba, conhece o segredo de toda magia.",
          "A falsidade não resiste à marca que Exu deixa no chão.",
          "Sou o senhor das firmezas; onde eu coloco a mão, a obra não cai.",
          "A Pemba é a ferramenta do mestre que sabe o que está fazendo.",
          "Limpo a sua aura e firmo o seu pensamento como uma rocha.",
          "O ponto riscado é o mapa da sua vitória contra a inveja.",
          "O traço de Pemba é a lei escrita que nenhum espírito inferior pode apagar.",
          "Sou a força que sustenta o cavalo e protege o médium.",
          "Na minha encruzilhada, a Pemba é a arma que desenha o seu sucesso.",
          "Laroiê, Exu Pemba! O guardião dos fundamentos e senhor da firmeza.",
        ]}]
      },
      {
        "id": "mangueira",
        "title": "Livro de Exu Mangueira",
        "entity": "Exu Mangueira",
        "greeting": "Laroiê, Exu Mangueira!",
        "intro": "Raízes profundas, sombra generosa e fruto doce para os que vêm com o coração aberto. Exu Mangueira carrega a sabedoria ancestral da floresta — a paciência da árvore que cresce devagar mas se torna irremovível. Sua proteção é vasta como a copa e sua cura, tão silenciosa quanto a seiva que alimenta.",
        "chapters": [{"num": 1, "verses": [
          "Minha raiz é profunda e o meu axé é o pulsar da própria terra.",
          "Sou a sombra que abriga os cansados e o tronco firme que sustenta o vento.",
          "A força da mangueira não está na folha, está na seiva da sabedoria que não seca.",
          "Onde houver desânimo, eu trago a energia verde da renovação espiritual.",
          "Caminho pela mata fechada e sei onde cada erro deve ser consertado.",
          "Não deixe que a inveja seque as suas folhas; eu dou o remédio da mata.",
          "Sou o mistério que protege quem busca a verdade com lealdade.",
          "A seiva que corre nas minhas veias é a proteção de quem tem fé.",
          "Quem me chama na mata, encontra um amigo e um guerreiro.",
          "O fruto da mangueira é doce para quem é bom, mas a casca amarga para quem vem com dolo.",
          "Sou o mestre da cura que limpa as dores da alma e do corpo.",
          "A escuridão do mato é o meu manto de invisibilidade contra a demanda.",
          "Não me peça o que é dos outros, peça para a sua própria árvore dar bons frutos.",
          "Minha presença é o abraço que te ergue nos dias de tempestade.",
          "Sou a sentinela das encruzilhadas da mata.",
          "Com a folha da mangueira, eu varro o mal e trago a paz.",
          "A sabedoria do mato não se aprende em livro, se sente no coração.",
          "Sou o equilíbrio entre o céu e a terra, entre a luz e a sombra.",
          "Quem tem Mangueira na frente, floresce mesmo em época de seca.",
          "Exu Mangueira chegou para dar firmeza aos seus passos e alegria à sua alma.",
        ]}]
      },
      {
        "id": "ze-do-coco",
        "title": "Livro de Exu Zé do Coco",
        "entity": "Exu Zé do Coco",
        "greeting": "Laroiê, Exu Zé do Coco!",
        "intro": "Simples no porte, poderoso na essência. Exu Zé do Coco é o trabalhor das matas e das praias, o que conhece o valor do simples e a força do que é verdadeiro. Sua sabedoria não vem de palácios — vem do chão, das palmas e do suor de quem nunca desistiu de sua verdade.",
        "chapters": [{"num": 1, "verses": [
          "A vida é como o coco: tem que ter força para quebrar a casca e paciência para beber a água.",
          "Sou do sertão, sou da beira do mar, sou de onde a fé me chamar para trabalhar.",
          "Meu machado não falha na madeira e minha palavra não falha na porteira.",
          "Não se engane com meu jeito simples; o veneno da cobra não me alcança e o feitiço do homem não me dobra.",
          "Quem planta o bem na terra seca, colhe milagre na hora da sede.",
          "Eu limpo o caminho com a palha e firmo a proteção na raiz.",
          "Zé do Coco não gosta de luxo, gosta de verdade e de coração limpo.",
          "Se o problema é duro, eu sou a marreta; se a vida é amarga, eu trago o doce do fruto.",
          "Sou a resistência da palmeira que enverga no vento, mas não quebra no tempo.",
          "Muitos olham para o alto, mas esquecem que é no chão que a vida se sustenta.",
          "Trago o mistério das matas e o frescor das águas em um só gole de fé.",
          "Quem caminha comigo aprende que a simplicidade é a maior de todas as magias.",
          "Não subestime quem anda descalço; eu sinto o perigo antes dele levantar poeira.",
          "Meu ponto é firmado na areia, mas minha palavra é escrita na pedra.",
          "Água de coco para os amigos, casca dura para os inimigos.",
          "Sou o equilíbrio entre o sol que queima e a sombra que abriga.",
          "Na minha mão, o pouco vira muito se houver gratidão.",
          "Vim de longe para te dizer: o que é seu, o vento não leva e o fogo não queima.",
          "Sou a força do caboclo na linha da esquerda.",
          "Zé do Coco chegou para mostrar que o essencial é invisível para quem só vê o ouro.",
        ]}]
      },
      {
        "id": "joaozinho-mariazinha",
        "title": "Livro de Joãozinho da Mata & Mariazinha",
        "entity": "Joãozinho da Mata & Mariazinha",
        "greeting": "Laroiê, Joãozinho da Mata! Laroiê, Mariazinha!",
        "intro": "Na linha da esquerda, a criança é o ser mais poderoso — porque não conhece o medo e não aprendeu a mentir. Joãozinho da Mata e Mariazinha carregam a pureza que corta o mal como faca nova, e a astúcia que só a inocência armada possui. Sua risada é exorcismo. Sua travessura, proteção.",
        "chapters": [{"num": 1, "verses": [
          "Quem entra na minha mata sem licença, sai dela sem caminho.",
          "O bicho que te assusta é o mesmo que eu domestico com um assobio.",
          "A cura está na folha que você pisa e não conhece.",
          "Sou o mistério do mato fechado e a luz que guia o caçador perdido.",
          "Não brigue com a natureza; ela sempre vence no final.",
          "Minha boneca é de pano, mas o meu feitiço é de aço.",
          "Brinco com o perigo como quem brinca de roda.",
          "Pequena no tamanho, mas gigante na hora de proteger quem tem fé.",
          "Dou um sorriso para os amigos e um nó na vida dos inimigos.",
          "Criança na esquerda não é brincadeira, é pureza que corta o mal.",
        ]}]
      },
    ]
  },
]
